### Create user
POST http://localhost:3000/users.json
Content-Type: application/json
 
{
 "first_name": "Bryce",
 "last_name": "Young",
 "user_name": "BamaQB1",
 "email": "bryce@test.com",
 "password": "password",
 "password_confirmation": "password"
}

###

### Create sessions
POST http://localhost:3000/sessions.json
Content-Type: application/json
 
 {
   "email": "bryce@test.com",
   "password": "password"
 }

###

###
GET http://localhost:3000/tailgates.json

###
POST http://localhost:3000/tailgates.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2MzQ5NTA2MzZ9.1uh7qe03j2Ur3O7H-zOmWNhUMot0nzNMrFPTu9_JQfA
Content-Type: application/json
 
{
 "user_id": 6,
 "game_id": 3,
 "name": "Test name",
 "description": "Many words...",
 "address": "Test address",
 "start_time": "2021-10-03T09:00:00-6:00",
 "end_time": "2021-10-03T13:00:00-6:00",
 "parking_available": false,
 "private_bathroom" :true, 
 "alcohol_allowed": false,
 "food_provided": false,
 "family_friendly": true,
 "tv_available": true
}

###
GET http://localhost:3000/tailgates/3.json

###

### Index games
GET http://localhost:3000/games/ncaa+football.json

### Create games
POST http://localhost:3000/games/ncaa+football.json



