### Create user
POST http://localhost:3000/users.json
Content-Type: application/json
 
{
 "first_name": "Bryce",
 "last_name": "Young",
 "user_name": "brycedude",
 "email": "bryce@test.com",
 "password": "password",
 "password_confirmation": "password"
}

### Show user
GET http://localhost:3000/users/1.json

###

### Create sessions
POST http://localhost:3000/sessions.json
Content-Type: application/json
 
 {
   "email": "kiel@test.com",
   "password": "password"
 }

###

### Index tailgates
GET http://localhost:3000/tailgates.json

### Create tailgate
POST http://localhost:3000/tailgates?q=ncaa+football.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzQ5OTk4ODV9.OkxtY1WcpfUZ8xt6mrAn6NWuGhMY1amD1BujHWRG9S0
Content-Type: application/json
 
{
 "name": "Test name",
 "description": "Many words...",
 "address": "Test address",
 "start_time": "2021-10-03T09:00:00-6:00",
 "end_time": "2021-10-03T13:00:00-6:00",
 "parking_available": false,
 "private_bathroom": true, 
 "alcohol_allowed": false,
 "food_provided": false,
 "family_friendly": true,
 "tv_available": true
}

### Show tailgate
GET http://localhost:3000/tailgates/2.json

### Update tailgate
PATCH http://localhost:3000/tailgates/4.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2MzQ5NTQxMDR9.3LVrSEvBRhusdV-jEwolEdodUgxpq800UcVK4Owbgqc
Content-Type: application/json
 
{
 "name": "Test name",
 "description": "Many words...",
 "address": "Test address",
 "start_time": "2021-10-03T09:00:00-6:00",
 "end_time": "2021-10-03T13:00:00-6:00",
 "parking_available": false,
 "private_bathroom": true, 
 "alcohol_allowed": false,
 "food_provided": false,
 "family_friendly": true,
 "tv_available": true
}

### Delete tailgate
DELETE http://localhost:3000/tailgates/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzQ5NTUwOTF9.zDY1yeRGv1RUvg7qu0eAqhBNOKrdeLf5Uk1Z2VN5Lhg

###

### Index games
GET http://localhost:3000/games?q=alabama-crimson-tide-football.json

### Create games
POST http://localhost:3000/games.json

### Show games
GET http://localhost:3000/games/5375467.json

###

### Create tailgate_users
POST http://localhost:3000/tailgate_users.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzU4NjY5MTd9.F_JLYllJBkHF00iSya8Z_NKhQrY_X3tkck90VhmjvWc
Content-Type: application/json
 
{
 "tailgate_id": 3,
 "game_id": 3
}

###

### Create lodgings
POST http://localhost:3000/lodgings.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU4NzA3Mjd9.3WLvAjU_XiG31FZ8BMEadrTLqlFdiDaKlmLg6ORJO5o
Content-Type: application/json

{
  "tailgate_id": 3,
  "lodging_type": "Hotel",
  "lodging_name": "Holiday Inn",
  "address": "201 Gemfile DR"
}

###

### Create Parkings
POST http://localhost:3000/parkings.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU4NzA3Mjd9.3WLvAjU_XiG31FZ8BMEadrTLqlFdiDaKlmLg6ORJO5o
Content-Type: application/json

{
  "tailgate_id": 3,
  "parking_type": "Street",
  "address": "504 Small Rd"
}